export const environment = {
  production: true,
  apiUrl: 'http://localhost:4201',
  authUrl: 'http://localhost:4201/auth',
  userUrl: 'http://localhost:4201/users/profile',
  usersUrl: 'http://localhost:4201/users',
  exerciseUrl: 'http://localhost:4201/exercise',
  setUrl: 'http://localhost:4201/set',
  workoutUrl: 'http://localhost:4201/workout',
  cardWorkoutUrl: 'http://localhost:4201/card_workout',
  statsUrl: 'http://localhost:4201/stat',
  dietUrl: 'http://localhost:4201/diet',
  nutrientUrl: 'http://localhost:4201/nutrients',
  foodUrl: 'http://localhost:4201/food',
  recipeUrl: 'http://localhost:4201/recipe',
  noteBookseUrl: 'http://localhost:4201/noteBook',
};
